In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [11]:
test["breed_category"]=-1
test["pet_category"]=-1

In [12]:
train = pd.concat([train, test])

In [13]:
train.reset_index(inplace=True)

In [14]:
train.drop(columns=["index", "pet_id", "issue_date", "listing_date"], inplace=True)

In [15]:
train["height(cm)"] = train["height(cm)"]/100
train.rename(columns={"height(cm)":"height(m)"},inplace=True)

In [16]:
color = pd.get_dummies(train["color_type"], drop_first=True)

In [17]:
train.head()

condition   color_type  length(m)  height(m)  X1  X2  breed_category  \
0        2.0  Brown Tabby       0.80     0.0778  13   9             0.0   
1        1.0        White       0.72     0.1419  13   9             0.0   
2        NaN        Brown       0.15     0.4090  15   4             2.0   
3        1.0        White       0.62     0.1782   0   1             0.0   
4        2.0        Black       0.50     0.1106  18   4             0.0   

   pet_category  
0             1  
1             2  
2             4  
3             2  
4             1

In [18]:
train.drop(columns=["color_type"],inplace=True)

In [19]:
train = pd.concat([color,train],axis=1)

In [20]:
test = train.loc[18834:,:].copy()
train = train.loc[0:18833,:]

In [21]:
test.reset_index(inplace=True)
test.drop(columns=["index"],inplace=True)

In [22]:
test.drop(columns=["breed_category", "pet_category"],inplace=True)

In [23]:
train["condition"].fillna(1,inplace=True)
test["condition"].fillna(1,inplace=True)

In [25]:
X = train.drop(columns=["breed_category", "pet_category"])
Y = train["breed_category"]

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(X, Y,test_size=0.2,random_state=42)

In [32]:
from sklearn.ensemble import GradientBoostingClassifier
GBC = GradientBoostingClassifier(random_state=42)
GBC.fit(x_train,y_train)
pred=GBC.predict(x_test)

In [33]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,pred))
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

[[1675  101   18]
 [ 287 1386    0]
 [ 114    0  186]]
0.8619591186620653
              precision    recall  f1-score   support

         0.0       0.81      0.93      0.87      1794
         1.0       0.93      0.83      0.88      1673
         2.0       0.91      0.62      0.74       300

    accuracy                           0.86      3767
   macro avg       0.88      0.79      0.83      3767
weighted avg       0.87      0.86      0.86      3767



In [131]:
train.head()

Apricot  Black  Black Brindle  Black Smoke  Black Tabby  Black Tiger  Blue  \
0        0      0              0            0            0            0     0   
1        0      0              0            0            0            0     0   
2        0      0              0            0            0            0     0   
3        0      0              0            0            0            0     0   
4        0      1              0            0            0            0     0   

   Blue Cream  Blue Merle  Blue Point  ...  White  Yellow  Yellow Brindle  \
0           0           0           0  ...      0       0               0   
1           0           0           0  ...      1       0               0   
2           0           0           0  ...      0       0               0   
3           0           0           0  ...      1       0               0   
4           0           0           0  ...      0       0               0   

   length(m)  height(m)        X1        X2  condition  breed_category  \
0   1.024225  -1.514343  1.169789  1.262750        2.0             0.0   
1   0.747384  -1.020842  1.169789  1.262750        1.0             0.0   
2  -1.225103   1.035542  1.475018 -0.157894        NaN             2.0   
3   0.401334  -0.741371 -0.814202 -1.010281        1.0             0.0   
4  -0.013926  -1.261818  1.932862 -0.157894        2.0             0.0   

   pet_category  
0             1  
1             2  
2             4  
3             2  
4             1  

[5 rows x 62 columns]

In [136]:
train.head()

Apricot  Black  Black Brindle  Black Smoke  Black Tabby  Black Tiger  Blue  \
0        0      0              0            0            0            0     0   
1        0      0              0            0            0            0     0   
2        0      0              0            0            0            0     0   
3        0      0              0            0            0            0     0   
4        0      1              0            0            0            0     0   

   Blue Cream  Blue Merle  Blue Point  ...  White  Yellow  Yellow Brindle  \
0           0           0           0  ...      0       0               0   
1           0           0           0  ...      1       0               0   
2           0           0           0  ...      0       0               0   
3           0           0           0  ...      1       0               0   
4           0           0           0  ...      0       0               0   

   length(m)  height(m)        X1        X2  condition  breed_category  \
0   1.024225  -1.514343  1.169789  1.262750        2.0             0.0   
1   0.747384  -1.020842  1.169789  1.262750        1.0             0.0   
2  -1.225103   1.035542  1.475018 -0.157894        1.0             2.0   
3   0.401334  -0.741371 -0.814202 -1.010281        1.0             0.0   
4  -0.013926  -1.261818  1.932862 -0.157894        2.0             0.0   

   pet_category  
0             1  
1             2  
2             4  
3             2  
4             1  

[5 rows x 62 columns]

In [137]:
from sklearn.decomposition import PCA

In [175]:
X = train.drop(columns=["breed_category", "pet_category"])
Y = train["breed_category"]

In [188]:
pca = PCA(0.98,random_state=42)
pca.fit(X)
X = pca.transform(X)
pca.n_components_

14

In [178]:
x_train,x_test,y_train,y_test = train_test_split(X, Y,test_size=0.2,random_state=42)

In [179]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import mean_squared_error

In [182]:
n = pca.n_components_

GBC = GradientBoostingClassifier(n_estimators=n, random_state=42)

GBC.fit(x_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [183]:
GBC.score(x_test,y_test)

0.8539952216617999

In [184]:
y = train["pet_category"]

In [185]:
x_train,x_test,y_train,y_test = train_test_split(X, y,test_size=0.2,random_state=42)

In [186]:
gbc = GradientBoostingClassifier(n_estimators=n, random_state=42)
gbc.fit(x_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=20,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [187]:
gbc.score(x_test,y_test)

0.838067427661269